export const IpcChannels = {
  scanStart: "scan:start",
  scanCancel: "scan:cancel",
  scanProgress: "scan:progress",
  scanComplete: "scan:complete",
  scanError: "scan:error",
  reportExport: "report:export",
  reportOpenWeb: "report:open-web",
  appVersion: "app:version",
  appPlatform: "app:platform",
  updateChecking: "update:checking",
  updateAvailable: "update:available",
  updateNotAvailable: "update:not-available",
  updateDownloadProgress: "update:download-progress",
  updateDownloaded: "update:downloaded",
  updateError: "update:error",
  updateInstall: "update:install",
  manifestExport: "manifest:export",
  windowMinimize: "window:minimize",
  windowMaximizeToggle: "window:maximize-toggle",
  windowClose: "window:close",
  windowState: "window:state",
  actionRun: "action:run",
  logsOpenFolder: "logs:open-folder",
  reportExportHtml: "report:export-html",
  appStateGet: "app-state:get",
  ignoreListUpdate: "ignore-list:update",
  cleanupPlan: "cleanup:plan",
  cleanupExecute: "cleanup:execute",
  cleanupHistory: "cleanup:history",
  appsList: "apps:list",
  appsUninstall: "apps:uninstall",
  appsLeftovers: "apps:leftovers"
} as const;

export type IpcChannel = (typeof IpcChannels)[keyof typeof IpcChannels];
