// AUTO-GENERATED by scripts/embed-ps-hash.mjs — do not edit by hand.
// Run `npm run embed-ps-hash` (or any build/test/dev script) to refresh.
//
// SHA-256 of resources/powershell/Invoke-FormatBuddyScan.ps1, anchored in
// the bundled main code so an attacker cannot bypass the integrity check
// by editing an external manifest alongside the script.

export const EXPECTED_PS_SCRIPT_HASH = "95fc04e56aa5756d7e2fc2c104d47c57fb3346345b6b116fb6f4fbd938641432";
