// AUTO-GENERATED by scripts/embed-ps-hash.mjs — do not edit by hand.
// Run `npm run embed-ps-hash` (or any build/test/dev script) to refresh.
//
// SHA-256 of resources/powershell/Invoke-FormatBuddyScan.ps1, anchored in
// the bundled main code so an attacker cannot bypass the integrity check
// by editing an external manifest alongside the script.

export const EXPECTED_PS_SCRIPT_HASH = "5f2d47034f6ad276c82e9d145b8607eaf52b57a63952d54e04e180f71e3bb51e";
