// AUTO-GENERATED by scripts/embed-ps-hash.mjs — do not edit by hand.
// Run `npm run embed-ps-hash` (or any build/test/dev script) to refresh.
//
// SHA-256 of resources/powershell/Invoke-FormatBuddyScan.ps1, anchored in
// the bundled main code so an attacker cannot bypass the integrity check
// by editing an external manifest alongside the script.

export const EXPECTED_PS_SCRIPT_HASH = "403aa7a336ca82aa0c603532e6c029cb9b6c31b772ac454f8f274b8535e80bf6";
