#!/usr/bin/env node
/**
 * Compute SHA-256 of the PowerShell scan script and emit it as a TypeScript
 * constant under src/shared/ps-script-hash.ts.
 *
 * This file is bundled into app.asar at build time so the expected digest
 * lives inside trusted main-process code, not an external manifest that an
 * attacker could rewrite alongside the script itself.
 *
 * Wired as `prebuild`, `predist:win`, and inside `dev` / `test` scripts.
 * Re-running is safe and produces deterministic output (only the hex digest
 * differs between PowerShell revisions).
 */
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, "..");
const scriptPath = join(projectRoot, "resources", "powershell", "Invoke-FormatBuddyScan.ps1");
const outPath = join(projectRoot, "src", "shared", "ps-script-hash.ts");

const contents = readFileSync(scriptPath);
const hash = createHash("sha256").update(contents).digest("hex");

const body = `// AUTO-GENERATED by scripts/embed-ps-hash.mjs — do not edit by hand.
// Run \`npm run embed-ps-hash\` (or any build/test/dev script) to refresh.
//
// SHA-256 of resources/powershell/Invoke-FormatBuddyScan.ps1, anchored in
// the bundled main code so an attacker cannot bypass the integrity check
// by editing an external manifest alongside the script.

export const EXPECTED_PS_SCRIPT_HASH = "${hash}";
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, body, "utf8");

console.info(`[embed-ps-hash] ${scriptPath}`);
console.info(`[embed-ps-hash]   → sha256 ${hash}`);
console.info(`[embed-ps-hash]   → ${outPath}`);
